name: Go

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:  

    - name: SSH into VM and run deploy script
      uses: garygrossgarten/github-action-ssh@release
      with:
        command: sh deploy.sh > /dev/null 2>&1
        host: 138.197.169.114
        username: root
        password: ${{ secrets.VM_ACCESS }}
